package ArduinoML.behavior;

/*Generated by MPS */


public class Action_BehaviorDescriptor extends Named_Element_BehaviorDescriptor {
  public Action_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Action";
  }
}
