package ArduinoML.behavior;

/*Generated by MPS */


public class And_Component_LCD_Temperature_BehaviorDescriptor extends And_Component_BehaviorDescriptor {
  public And_Component_LCD_Temperature_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.And_Component_LCD_Temperature";
  }
}
