package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class And_Component_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public And_Component_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.And_Component";
  }
}
