package ArduinoML.behavior;

/*Generated by MPS */


public class And_Test_BehaviorDescriptor extends Test_BehaviorDescriptor {
  public And_Test_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.And_Test";
  }
}
