package ArduinoML.behavior;

/*Generated by MPS */


public class AndComponentLCDTemperature_BehaviorDescriptor extends AndComponent_BehaviorDescriptor {
  public AndComponentLCDTemperature_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.AndComponentLCDTemperature";
  }
}
