package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class AndComponent_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AndComponent_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.AndComponent";
  }
}
