package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class AndTest_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AndTest_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.AndTest";
  }
}
