package ArduinoML.behavior;

/*Generated by MPS */


public class AndTest_BehaviorDescriptor extends Test_BehaviorDescriptor {
  public AndTest_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.AndTest";
  }
}
