package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 7:
        return new Machine_State_BehaviorDescriptor();
      case 9:
        return new Sketch_BehaviorDescriptor();
      case 4:
        return new Component_IN_BehaviorDescriptor();
      case 5:
        return new Component_OUT_BehaviorDescriptor();
      case 0:
        return new Action_BehaviorDescriptor();
      case 3:
        return new And_Test_BehaviorDescriptor();
      case 6:
        return new LCD_BehaviorDescriptor();
      case 1:
        return new And_Component_BehaviorDescriptor();
      case 8:
        return new Or_Test_BehaviorDescriptor();
      case 2:
        return new And_Component_LCD_Temperature_BehaviorDescriptor();
      case 10:
        return new Use_Previous_State_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"ArduinoML.structure.Action", "ArduinoML.structure.And_Component", "ArduinoML.structure.And_Component_LCD_Temperature", "ArduinoML.structure.And_Test", "ArduinoML.structure.Component_IN", "ArduinoML.structure.Component_OUT", "ArduinoML.structure.LCD", "ArduinoML.structure.Machine_State", "ArduinoML.structure.Or_Test", "ArduinoML.structure.Sketch", "ArduinoML.structure.Use_Previous_State"};
}
