package ArduinoML.behavior;

/*Generated by MPS */


public class Component_OUT_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Component_OUT_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Component_OUT";
  }
}
