package ArduinoML.behavior;

/*Generated by MPS */


public abstract class Component_BehaviorDescriptor extends Named_Element_BehaviorDescriptor {
  public Component_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Component";
  }
}
