package ArduinoML.behavior;

/*Generated by MPS */


public class Component_IN_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Component_IN_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Component_IN";
  }
}
