package ArduinoML.behavior;

/*Generated by MPS */


public class LCD_BehaviorDescriptor extends Component_OUT_BehaviorDescriptor {
  public LCD_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.LCD";
  }
}
