package ArduinoML.behavior;

/*Generated by MPS */


public class Machine_State_BehaviorDescriptor extends Named_Element_BehaviorDescriptor {
  public Machine_State_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Machine_State";
  }
}
