package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Named_Element_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Named_Element_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Named_Element";
  }
}
