package ArduinoML.behavior;

/*Generated by MPS */


public class Or_Test_BehaviorDescriptor extends Test_BehaviorDescriptor {
  public Or_Test_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Or_Test";
  }
}
