package ArduinoML.behavior;

/*Generated by MPS */


public class OrTest_BehaviorDescriptor extends Test_BehaviorDescriptor {
  public OrTest_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.OrTest";
  }
}
