package ArduinoML.behavior;

/*Generated by MPS */


public class Signal_BehaviorDescriptor extends Named_Element_BehaviorDescriptor {
  public Signal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Signal";
  }
}
