package ArduinoML.behavior;

/*Generated by MPS */


public class Transition_BehaviorDescriptor extends Named_Element_BehaviorDescriptor {
  public Transition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Transition";
  }
}
