package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Use_Previous_State_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Use_Previous_State_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Use_Previous_State";
  }
}
