package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class UsePreviousState_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public UsePreviousState_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.UsePreviousState";
  }
}
