package ArduinoML.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class AndComponent_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.appendNewLine();
    if (SPropertyOperations.getString_def(SLinkOperations.getTarget(node, "component", false), "signal", "analogic").equalsIgnoreCase("digital")) {
      this.append("        ");
      this.append("writeDigital");
    } else if (SPropertyOperations.getString_def(SLinkOperations.getTarget(node, "component", false), "signal", "analogic").equalsIgnoreCase("analogic")) {
      this.append("        ");
      this.append("writeAnalogic");
    }
    this.append("(");
    this.append(SPropertyOperations.getString(node, "value"));
    this.append(");");
    if (SLinkOperations.getTarget(node, "and", true) != null) {
      appendNode(SLinkOperations.getTarget(node, "and", true));
    }
  }
}
