package ArduinoML.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class AndComponentLCDTemperature_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.appendNewLine();
    this.append("        ");
    this.append("lcd.setCursor(0, 1);");
    this.appendNewLine();
    this.append("        ");
    this.append("lcd.print(\"");
    this.append(SPropertyOperations.getString(node, "sentence"));
    this.append("\");");
    this.appendNewLine();
    this.append("        ");
    this.append("lcd.setCursor(0, 2);");
    this.appendNewLine();
    this.append("        ");
    this.append("lcd.print(");
    this.append("digitalRead(");
    this.append(String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(node, "componentSensorTemperature", false), "pin")));
    this.append(")");
    this.append(");");
    if (SLinkOperations.getTarget(node, "and", true) != null) {
      appendNode(SLinkOperations.getTarget(node, "and", true));
    }
  }
}
