package ArduinoML.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class AndTest_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    if (SPropertyOperations.getString_def(SLinkOperations.getTarget(node, "component", false), "signal", "analogic").equalsIgnoreCase("digital")) {
      this.append("readDigital");
    } else if (SPropertyOperations.getString_def(SLinkOperations.getTarget(node, "component", false), "signal", "analogic").equalsIgnoreCase("analogic")) {
      this.append("readAnalogic");
    }
    this.append("(");
    this.append(String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(node, "component", false), "pin")));
    this.append(") ");
    this.append(SPropertyOperations.getString_def(node, "operator", "=="));
    this.append(" ");
    this.append(SPropertyOperations.getString(node, "value"));
    if (SLinkOperations.getTarget(node, "and", true) != null) {
      this.append(" && ");
      appendNode(SLinkOperations.getTarget(node, "and", true));
    }
  }
}
