package ArduinoML.sandbox;

/*Generated by MPS */


public class TurnsOnLight {


  public static void main(String[] args) {
    System.out.println("int " + "TurnsOnLight" + " = " + "" + ";");
    System.out.println("void setup() {");
    System.out.println("pinMode(" + "11" + ", INPUT)");
    System.out.println("pinMode(" + "8" + ", OUTPUT)");
    System.out.println("}");
    System.out.println("void loop() {");
    System.out.print("int " + "SignalToTurnsLightOn" + " = ");
    System.out.print("analogicRead");
    System.out.print("(" + "11" + ");");
    System.out.println("}");
  }


}
