package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum SignalType {
  analogic("analogic", "analogic"),
  digital("digital", "digital");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<SignalType> getConstants() {
    List<SignalType> list = ListSequence.fromList(new LinkedList<SignalType>());
    ListSequence.fromList(list).addElement(SignalType.analogic);
    ListSequence.fromList(list).addElement(SignalType.digital);
    return list;
  }

  public static SignalType getDefault() {
    return SignalType.analogic;
  }

  public static SignalType parseValue(String value) {
    if (value == null) {
      return SignalType.getDefault();
    }
    if (value.equals(SignalType.analogic.getValueAsString())) {
      return SignalType.analogic;
    }
    if (value.equals(SignalType.digital.getValueAsString())) {
      return SignalType.digital;
    }
    return SignalType.getDefault();
  }

  private String myValue;

  SignalType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
