package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Signal_Type {
  analogic("analogic", "analogic"),
  digital("digital", "digital");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Signal_Type> getConstants() {
    List<Signal_Type> list = ListSequence.fromList(new LinkedList<Signal_Type>());
    ListSequence.fromList(list).addElement(Signal_Type.analogic);
    ListSequence.fromList(list).addElement(Signal_Type.digital);
    return list;
  }

  public static Signal_Type getDefault() {
    return Signal_Type.analogic;
  }

  public static Signal_Type parseValue(String value) {
    if (value == null) {
      return Signal_Type.getDefault();
    }
    if (value.equals(Signal_Type.analogic.getValueAsString())) {
      return Signal_Type.analogic;
    }
    if (value.equals(Signal_Type.digital.getValueAsString())) {
      return Signal_Type.digital;
    }
    return Signal_Type.getDefault();
  }

  private String myValue;

  Signal_Type(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
